variable "ami" {
  type        = string
  description = "The Amazon Machine Image to use when launching the EC2 Instance."

}

variable "subnet_id" {
  type        = string
  description = "The ID of the Subnet to launch the instance into."

  validation {
    condition     = length(regexall("^subnet-[\\w]+$", var.subnet_id)) == 1
    error_message = "The subnet_id must match the pattern ^subnet-[\\w]+$"
  }
}

variable "instance_type" {
  type        = string
  description = "The type of instance to launch."
  default     = "t3.micro"
}

variable "name_prefix" {
  type        = string
  description = "The prefix to apply to the beginning of names generated by this module."
}

variable "tags" {
  type        = map(string)
  description = "Key/Value pairs to pass to AWS as Tags."
  default     = {}

}

variable "instance_count" {
  type        = number
  description = "The number of instances to launch."
  default     = 0
  validation {
    condition     = can(parseint(tostring(var.instance_count), 10))
    error_message = "The instance count must be a whole number."
  }

  validation {
    condition     = var.instance_count >= 0
    error_message = "The instance count can not be negative."
  }
}